#server.port=8090
#Sserver.contextPath=/restaurant
spring.profiles.active=dev


#------------Database Config---------------#
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/restaurant
spring.datasource.username=root
spring.datasource.password=Pass@321
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.security.user.name=Kunal
spring.security.user.password=Pass@321


#------------API Config-------------------------#
URL_EDAMAM_HOST=https://api.edamam.com/

EDAMAM_APPLICATION_ID_RECIPE_SEARCH=1e92f47f
EDAMAM_APPLICATION_KEY_RECIPE_SEARCH=77eedf2c933732517c22c5bd706dae6e
EDAMAM_APPLICATION_ID_NUTRITION_ANALYSIS=0c862b0d
EDAMAM_APPLICATION_KEY_NUTRITION_ANALYSIS=e1954902f7f7b1d1ea1e3bfce85347fe


#--------------Redis Config-------------------#
spring.redis.host=localhost
spring.redis.port=6000
